### ISSUE TITLE
In Marlin 2.1.2, Ender-2 fails with error: 'LCD_PINS_RS' was not declared in this scope

### ISSUE THREAD

**Issue by probonopd** [probonopd/marlin-builds#1]
When upgrading from Marlin 2.1 to 2.1.2, Ender-2 compilation fails with

```
Compiling .pio/build/melzi_optimized/src/src/lcd/dogm/status_screen_DOGM.cpp.o
In file included from Marlin/src/lcd/dogm/../../inc/../pins/pins.h:319:0,
                 from Marlin/src/lcd/dogm/../../inc/MarlinConfig.h:34,
                 from Marlin/src/lcd/dogm/HAL_LCD_class_defines.h:24,
                 from Marlin/src/lcd/dogm/marlinui_DOGM.h:31,
                 from Marlin/src/lcd/dogm/marlinui_DOGM.cpp:42:
Marlin/src/lcd/dogm/marlinui_DOGM.cpp: In static member function 'static void MarlinUI::init_lcd()':
Marlin/src/lcd/dogm/../../inc/../pins/sanguino/pins_MELZI_CREALITY.h:82:38: error: 'LCD_PINS_RS' was not declared in this scope
   #define DOGLCD_CS                  LCD_PINS_RS
                                      ^
Marlin/src/lcd/dogm/marlinui_DOGM.h:231:23: note: in expansion of macro 'DOGLCD_CS'
     #define U8G_PARAM DOGLCD_CS, DOGLCD_A0                      // HW-SPI
                       ^~~~~~~~~
Marlin/src/lcd/dogm/marlinui_DOGM.cpp:267:14: note: in expansion of macro 'U8G_PARAM'
     u8g.init(U8G_PARAM);
              ^~~~~~~~~
Marlin/src/lcd/dogm/../../inc/../pins/sanguino/pins_MELZI_CREALITY.h:82:38: note: suggested alternative: 'LCD_PINS_D4'
   #define DOGLCD_CS                  LCD_PINS_RS
                                      ^
Marlin/src/lcd/dogm/marlinui_DOGM.h:231:23: note: in expansion of macro 'DOGLCD_CS'
     #define U8G_PARAM DOGLCD_CS, DOGLCD_A0                      // HW-SPI
                       ^~~~~~~~~
Marlin/src/lcd/dogm/marlinui_DOGM.cpp:267:14: note: in expansion of macro 'U8G_PARAM'
     u8g.init(U8G_PARAM);
              ^~~~~~~~~
*** [.pio/build/melzi_optimized/src/src/lcd/dogm/marlinui_DOGM.cpp.o] Error 1
========================= [FAILED] Took 39.47 seconds =========================

Environment      Status    Duration
---------------  --------  ------------
melzi_optimized  FAILED    00:00:39.470
==================== 1 failed, 0 succeeded in 00:00:39.470 ====================
Error: Process completed with exit code 1.
```

It was working in Marlin 2.1.

**Comment by probonopd** [comment]
Reported upstream
* https://github.com/MarlinFirmware/Marlin/issues/25204
